name: "Build and Push Docker image to Docker Hub"

on:
  push:
    branches:
      - main

env:
    VERSION:  ${{(cat version.txt)+1}}
      
jobs:
  buildandpushdockerimage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

     - name: Login into DockerHub
       run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t docker.io/arigelarajesh45/gamedemo:${{env.VERSION}}
        docker push docker.io/arigelarajesh45/gamedemo:${{env.VERSION}}