name: "Run Container Scan"

on:
  push:
    branches:
      - main

jobs:
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker Image from Docker Hub
        run: docker pull docker.io/arigelarajesh45/gamedemo:1

      - name: Debug Pulled Image
        run: docker images

      - name: Save Docker Image to Workspace
        run: |
          echo "Saving image to ${{ github.workspace }}/gamedockerimage.tar"
          mkdir -p ${{ github.workspace }}
          docker save -o ${{ github.workspace }}/gamedockerimage.tar docker.io/arigelarajesh45/gamedemo:1
          echo "Saved image successfully!"
          ls -la ${{ github.workspace }}

      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          input: ${{ github.workspace }}/gamedockerimage.tar
          exit-code: "0"
          severity: "CRITICAL,HIGH"
